/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eStoreSearch;

//import jdk.internal.agent.resources.agent;

import static org.junit.Assert.*;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.lang.model.util.ElementScanner6;
import org.junit.Before;
import org.junit.Test;

public class EStoreSearchTest {
  // String VproductID = "012345";
  // static String VproductID1 = "999999";
  // String VproductIDinvalid =  "01234567-";
  // String Vprice = "25.99";
  // String Vyear = "2020";
  // String Vdescription = "Java programming";
  // String Vauthor = "mir ali";
  // String Vpublisher = "Undergrad uofg";
  // String keyWord[] = Vdescription.split(" ");
  // String falsedescription = "Different description";
  // String keyWord2[] = falsedescription.split(" ");

  // public HashMap<String,List<Integer>> testmap = new HashMap<>();
  // public ArrayList<Product> productsListtest = new ArrayList<Product>();

  // @Before public void addtolist() {
  //     productsListtest.add(new Book(Vprice, Vyear, Vdescription, Vpublisher, Vauthor, VproductID));
  //     Arrays.toString(productsListtest.toArray());
  // }
  // @Test public void matchKeyTest(){

  //     EStoreSearch testObj = new EStoreSearch();
  //     assertFalse(testObj.matchKey(keyWord2,Vdescription));
  //     assertTrue(testObj.matchKey(keyWord,Vdescription));
  // }

  // @Test public void matchKeyTokenTest(){

  //     EStoreSearch testObj = new EStoreSearch();
  //     assertFalse(testObj.matchKey(keyWord2,Vdescription));
  //     assertTrue(testObj.matchKey(keyWord,Vdescription));
  // }

  //  @Test public void TestisNull() {
  //  EStoreSearch testObj = new EStoreSearch();
  //  boolean result = testObj.isNullOrEmpty(VproductID1);
  //  assertFalse(result);
  // // assertFalse(EStoreSearch.isNullOrEmpty(empty));

  // }

  // @Test public void TestcheckproductID() {
  //     EStoreSearch testObj = new EStoreSearch();
  //     boolean result = testObj.checkProductID(VproductID);
  //     assertFalse(result);

  // }

  // @Test public void Testcheckaddhash () {

  //     String checkdescription = "java";
  //     testmap.put("programming", new ArrayList<Integer>());
  //     EStoreSearch testObj = new EStoreSearch();

  //     testObj.addToHashMap(checkdescription);

  // }

  // @Test public void TestsearchHash() {
  //     String checkdescription = "java";
  //     testmap.get(checkdescription);
  //     EStoreSearch testObj = new EStoreSearch();

  //     testObj.searchHashMap(checkdescription);

  // }

  // @Test public void TestParsefromFile() {
  //     String filename = "./src/test/resources/file.txt";
  //     EStoreSearch testObj = new EStoreSearch();
  //     File file = new File("./src/test/resources/file.txt");

  //   try{
  //     PrintWriter writer = new PrintWriter(filename, "UTF-8");

  //     for (Product contents : productsListtest) {
  //       writer.println(contents);
  //     }

  //     testObj.saveToFile(filename);

  //     writer.close();
  // }catch (FileNotFoundException e) {

  // } catch (UnsupportedEncodingException e ){

  // } catch (NoSuchElementException e){

  // }
  //    assertTrue(file.exists());
  // }

  // @Test public void ListToFile() {
  //     String filename = "./src/test/resources/file.txt";
  //     EStoreSearch testObj = new EStoreSearch();
  //     File file = new File("./src/test/resources/file.txt");

  //         testObj.fileToList(filename);

  // }
}
