/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eStoreSearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class ProductTest {

  //   String VproductID = "012345";
  //   String Vprice = "25.99";
  //   String Vyear = "2020";
  //   String Vdescription = "Intro to JUNIT";
  //   String Vauthor = "mir ali";
  //   String Vpublisher = "Undergrad uofg";
  //   String Vauthor1 = "fei song";
  //   String Vpublisher1 = "grad uofg";

  //   Product classproducttest = new Product(Vprice, Vyear, Vdescription, VproductID);


  // @Test public void testProdcutID(){
  //   classproducttest.setProductID(VproductID);
  //   assertEquals("The productID should be 012345",VproductID, classproducttest.getProductID());
  // }

  // @Test public void testdescription(){
  //   classproducttest.setDescription(Vdescription);
  //   assertEquals("The description should be Intro to JUNIT",Vdescription, classproducttest.getDescription());
  // }

  // @Test public void testprice(){
  //   classproducttest.setPrice(Vprice);
  //   assertEquals("The price should be 25.99",Vprice, classproducttest.getPrice());
  // }

  // @Test public void testyear(){
  //   classproducttest.setYear(Vyear);
  //   assertEquals("The year should be 2020", Vyear, classproducttest.getYear());
  // }
  

  // @Test public void EqualityCheck(){
  //   Product classproducttestcompar = new Product(Vprice, Vyear, Vdescription, VproductID);
  //   assertFalse("The Products match", classproducttest.equals(classproducttestcompar));

  //   classproducttestcompar = new Product(Vprice, "2003", "Interesting description", VproductID);
  //   assertFalse("Different year and description", classproducttest.equals(classproducttestcompar));

  // }
}
